CC = gcc

CFLAGS = -g -Wall -Wpedantic -std=c17

LDFLAGS =
LDLIBS =

.PHONY: all
all: clean hole copy copy-nobuf

hole:
copy:
copy-nobuf:

.PHONY: clean
clean:
	rm -rf *.o a.out hole copy copy-nobuf file-with-hole file-copied
